spring:
    data:
        mongodb:
            host: ds117136.mlab.com
            port: 17136
            database: lab7_arsw
            username: Hakuto
            password: Arsw123 
    redis:
        host: ec2-35-160-57-197.us-west-2.compute.amazonaws.com
        port: 6379